
services:
  - type: web
    name: telegram-webhook-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_HOST
        value: https://telegram-rotating-bot.onrender.com
